transaction_type_group_index:
    path:     /
    defaults: { _controller: "AppBundle:TransactionTypeGroup:index" }
    methods:  GET

transaction_type_group_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TransactionTypeGroup:show" }
    methods:  GET

transaction_type_group_new:
    path:     /new
    defaults: { _controller: "AppBundle:TransactionTypeGroup:new" }
    methods:  [GET, POST]

transaction_type_group_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TransactionTypeGroup:edit" }
    methods:  [GET, POST]

transaction_type_group_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TransactionTypeGroup:delete" }
    methods:  DELETE
