transaction_type_index:
    path:     /
    defaults: { _controller: "AppBundle:TransactionType:index" }
    methods:  GET

transaction_type_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TransactionType:show" }
    methods:  GET

transaction_type_new:
    path:     /new
    defaults: { _controller: "AppBundle:TransactionType:new" }
    methods:  [GET, POST]

transaction_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TransactionType:edit" }
    methods:  [GET, POST]

transaction_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TransactionType:delete" }
    methods:  DELETE
