AppBundle\Entity\AccountGroup:
    type: entity
    table: account_group
    repositoryClass: AppBundle\Repository\AccountGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        description:
            type: text
            length: 65535
            nullable: true
        code:
            type: string
            length: '50'
            nullable: true
        level:
            type: smallint
        type:
            fixed: true
            type: string
            length: 1
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        parent:
            targetEntity: AccountGroup
            fetch: EXTRA_LAZY
            joinColumn:
                onDelete: CASCADE
    lifecycleCallbacks:
        prePersist: [ setCreatedAt ]
        preUpdate: [ setUpdatedAt ]
