AppBundle\Entity\Account:
    type: entity
    table: account
    repositoryClass: AppBundle\Repository\AccountRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        description:
            type: text
            length: 65535
            nullable: true
        code:
            type: string
            length: '30'
            nullable: true
        dc:
            type: string
            length: '1'
        type:
            fixed: true
            type: string
            length: 1
        initialBalance:
            type: decimal
            precision: '14'
            scale: '4'
            nullable: true
            column: initial_balance
        isCash:
            type: boolean
            column: is_cash
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        group:
            targetEntity: AccountGroup
            joinColumn:
                onDelete: CASCADE
                fetch: LAZY
    lifecycleCallbacks:
        prePersist: [ setCreatedAt ]
        preUpdate: [ setUpdatedAt ]
