AppBundle\Entity\Transaction:
    type: entity
    table: transaction
    repositoryClass: AppBundle\Repository\TransactionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        description:
            type: text
            length: 65535
        date:
            type: date
            column: date
        isPosted:
            type: boolean
            column: is_posted
        postDate:
            type: datetime
            column: posted_at
            nullable: true
        isCanceled:
            type: boolean
            column: is_canceled
            default: 0
        status:
            type: string
            length: '30'
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        user:
            targetEntity: User
        type:
            targetEntity: TransactionType
    manyToMany:
        tags:
            targetEntity: Tag
            joinTable:
                name: transactions_tags
                joinColumns:
                    transaction_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAt ]
        preUpdate: [ setUpdatedAt ]
