AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '30'
            unique: true
        password:
            type: text
            length: 65535
        firstName:
            type: string
            length: '40'
            column: first_name
        middleName:
            type: string
            length: '40'
            column: middle_name
        lastName:
            type: string
            length: '40'
            column: last_name
        email:
            type: string
            length: '80'
            nullable: true
        contactNumber:
            type: string
            length: '40'
            nullable: true
            column: contact_number
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks:
        prePersist: [ setCreatedAt ]
        preUpdate: [ setUpdatedAt ]
